backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/site/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "/site/content/kit/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Blog Post Title", name: "title", widget: "string"}
      - {label: "Page Order", name: "weight", widget: "string", hint: "Developer note: I've numbered these as multiples of 10 to allow for easy insertion of additional pages if needed."}
      - {label: "Content Type", name: "contenttype", widget: hidden, default: "toolkit"}
      - {label: "Created Date", name: "date", widget: "datetime"}
      - {label: "Social Media / Search Description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, bulleted-list, numbered-list, heading-two]}